export { RatClient } from "./client";
export type { RatClientOptions } from "./client";
export type { ClientConfig, RequestInterceptor, ResponseInterceptor } from "./config";
export {
  RatError,
  AuthenticationError,
  AuthorizationError,
  NotFoundError,
  ConflictError,
  ValidationError,
  ServerError,
  ConnectionError,
} from "./errors";

export type {
  HealthResponse,
  FeaturesResponse,
  PluginFeature,
  Pipeline,
  PipelineConfig,
  PipelineListResponse,
  CreatePipelineRequest,
  UpdatePipelineRequest,
  CreatePipelineResponse,
  PipelineVersion,
  PipelineVersionListResponse,
  PublishResponse,
  RollbackRequest,
  RollbackResponse,
  Layer,
  MergeStrategy,
  Run,
  RunListResponse,
  CreateRunRequest,
  CreateRunResponse,
  RunLog,
  RunLogsResponse,
  RunStatus,
  QueryColumn,
  QueryResult,
  QueryRequest,
  TableInfo,
  TableDetail,
  TableListResponse,
  SchemaEntry,
  SchemaResponse,
  UpdateTableMetadataRequest,
  FileInfo,
  FileContent,
  FileListResponse,
  Namespace,
  NamespaceListResponse,
  UpdateNamespaceRequest,
  TriggerType,
  PipelineTrigger,
  TriggerListResponse,
  CreateTriggerRequest,
  UpdateTriggerRequest,
  LandingZone,
  LandingFile,
  LandingZoneListResponse,
  LandingFileListResponse,
  CreateLandingZoneRequest,
  UpdateLandingZoneRequest,
  LandingZoneUploadConfig,
  CronConfig,
  PipelineSuccessConfig,
  WebhookConfig,
  FilePatternConfig,
  CronDependencyConfig,
  SampleFileInfo,
  SampleFileListResponse,
  SampleFileUploadResponse,
  PreviewRequest,
  PreviewResponse,
  PreviewColumn,
  PhaseProfile,
  PreviewLogEntry,
  QualityTest,
  QualityTestListResponse,
  CreateQualityTestRequest,
  CreateQualityTestResponse,
  QualityTestResult,
  QualityRunResponse,
  LineageNode,
  LineageEdge,
  LineageGraph,
  RetentionConfig,
  RetentionConfigResponse,
  ReaperStatus,
  PipelineRetentionResponse,
  ZoneLifecycleResponse,
  ZoneLifecycleRequest,
  AuditEntry,
  AuditListResponse,
  ShareAccess,
  ShareListResponse,
  ShareResourceRequest,
  TransferOwnershipRequest,
  Webhook,
  WebhookListResponse,
  CreateWebhookRequest,
  CreateWebhookResponse,
} from "./models";

export { HealthResource } from "./resources/health";
export { PipelinesResource } from "./resources/pipelines";
export { RunsResource } from "./resources/runs";
export { QueryResource } from "./resources/query";
export { TablesResource } from "./resources/tables";
export { StorageResource } from "./resources/storage";
export { NamespacesResource } from "./resources/namespaces";
export { TriggersResource } from "./resources/triggers";
export { QualityResource } from "./resources/quality";
export { LineageResource } from "./resources/lineage";
export { RetentionResource } from "./resources/retention";
