export default {
  "---pipelines": { type: "separator", title: "Pipelines" },
  "sql-pipelines": "SQL Pipelines",
  "python-pipelines": "Python Pipelines",
  "merge-strategies": "Merge Strategies",
  "incremental-pipelines": "Incremental Pipelines",
  "landing-zones": "Landing Zones",
  "---features": { type: "separator", title: "Platform Features" },
  "quality-tests": "Quality Tests",
  scheduling: "Scheduling",
  "pipeline-triggers": "Pipeline Triggers",
  versioning: "Versioning",
  "query-console": "Query Console",
  lineage: "Lineage",
  "data-retention": "Data Retention",
  "table-metadata": "Table Metadata",
  "---plugins": { type: "separator", title: "Plugins" },
  "writing-plugins": "Writing Plugins",
  "runner-plugins": "Runner Plugins",
  "platform-plugins": "Platform Plugins",
  "portal-plugins": "Portal Plugins",
  "---best-practices": { type: "separator", title: "Best Practices" },
  "best-practices": "Best Practices",
};
