version: "2"
output:
  formats:
    text:
      path: stdout
  sort-order:
    - linter
    - file
linters:
  enable:
    - gocritic
    - prealloc
    - revive
  disable:
    - exhaustruct
    - gochecknoglobals
    - misspell
    - varnamelen
    - wrapcheck
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - fmt.Fprintf
        - fmt.Fprintln
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeValCopy
      enabled-tags:
        - diagnostic
        - performance
      disabled-tags:
        - style
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
          disabled: true
        - name: increment-decrement
        - name: var-naming
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - prealloc
        path: _test\.go
      - linters:
          - revive
        path: _test\.go
        text: unused-parameter
      - linters:
          - staticcheck
        path: _test\.go
        text: SA1019
      - linters:
          - staticcheck
        path: _test\.go
        text: SA1012
      - linters:
          - errcheck
          - gocritic
          - govet
          - ineffassign
          - misspell
          - prealloc
          - revive
          - staticcheck
          - unused
        path: gen/
    paths:
      - gen
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
