export default {
  overview: "Overview",
  pipelines: "Pipelines",
  runs: "Runs",
  query: "Query",
  tables: "Tables",
  storage: "Storage",
  "landing-zones": "Landing Zones",
  triggers: "Triggers",
  "quality-tests": "Quality Tests",
  schedules: "Schedules",
  namespaces: "Namespaces",
  retention: "Retention",
  lineage: "Lineage",
  health: "Health",
  webhooks: "Webhooks",
  sharing: "Sharing",
  audit: "Audit",
};
